rel_projection = {
    'Antonym': ['antonym'], 
    'AtLocation': ['at','location'], 
    'CapableOf': ['capable', 'of'], 
    'Causes': ['cause'],
    'CausesDesire': ['cause', 'desire'],
    'CreatedBy': ['create', 'by'],
    'DefinedAs': ['define', 'as'],
    'DerivedFrom': ['derive', 'from'],
    'Desires': ['desire'],
    'DistinctFrom': ['distinct', 'from'],
    'Entails': ['entail'],
    'EtymologicallyDerivedFrom': ['etymological', 'derive', 'from'],
    'EtymologicallyRelatedTo': ['etymological', 'relate', 'to'],
    'FormOf': ['form', 'of'], 
    'HasA': ['has', 'a'],
    'HasContext': ['has', 'context'],
    'HasFirstSubevent': ['has', 'first', 'subevent'],
    'HasLastSubevent': ['has', 'last', 'subevent'],
    'HasPrerequisite': ['has', 'prerequisite'],
    'HasProperty': ['has', 'property'],
    'HasSubevent': ['has', 'subevent'],
    'InstanceOf':  ['instance', 'of'], 
    'IsA':  ['is', 'a'],
    'LocatedNear': ['locate', 'near'],
    'MadeOf':  ['made', 'of'],
    'MannerOf':  ['manner', 'of'],
    'MotivatedByGoal':  ['motivate', 'by', 'goal'],
    'NotCapableOf': ['not', 'capable', 'of'],
    'NotDesires':  ['not', 'desire'],
    'NotHasProperty':  ['not', 'has', 'property'],
    'PartOf':  ['part', 'of'],
    'ReceivesAction':  ['receive', 'action'],
    'RelatedTo':  ['relate', 'to'],
    'SimilarTo':  ['similar', 'to'],
    'SymbolOf':  ['symbol', 'of'],
    'Synonym': ['synonym'],
    'UsedFor': ['use', 'for'],
    'dbpedia': ['dbpedia'],
}
    

 